#spring:
#  profiles:
#      group:
#        dev: dev, oauth
#
#app:
#  auth:
#    tokenSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
#    tokenExpiry: 2592000000 # 30일
#
#

app:
  auth:
    tokenSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    tokenExpiry: 2592000000 # 30일
# CD TEST
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

spring:
  datasource:
    url: jdbc:postgresql://daedong-bread-dev-db.chgx9pjvwafw.ap-northeast-2.rds.amazonaws.com:5432/daedongbread
    username: postgres
    password: postgre12
    driver-class-name: org.postgresql.Driver

swagger-info:
  title: Daedong BreadMap REST API
  description: Depromeet 10th Team 7
  version: 1.0.0