spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/daedongBreadShop
    username: sa
    password:
    driver-class-name: org.h2.Driver

app:
  auth:
    tokenSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    tokenExpiry: 11111111
    refreshTokenExpiry: 111111111