#spring:
#  profiles:
#      group:
#        dev: dev, oauth
#
#app:
#  auth:
#    tokenSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
#    tokenExpiry: 2592000000 # 30일
#
#

app:
  auth:
    tokenSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    tokenExpiry: 2592000000 # 30일
# CD TEST
spring:
  datasource:
    url: jdbc:postgresql://${rds.hostname}:5432/${rds.dbname}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: ${rds.driver}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

swagger-info:
  title: Daedong BreadMap REST API
  description: Depromeet 10th Team 7
  version: 1.0.0