spring:
  profiles:
      group:
        dev: dev, oauth

app:
  auth:
    tokenSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    tokenExpiry: 604800000 # 7일
    refreshTokenExpiry: 7776000000 # 90일