# 개발서버 Deploy workflow - develop 브랜치
name: DaeDong-BreadMap dev server CD

on:
  push:
    branches:
      - 'feature/26'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate deployment package # (1)
        run: |
          mkdir -p deploy-dev
          cp build/libs/*.jar deploy-dev/application.jar
          cp Procfile deploy-dev/Procfile
          cp -r .ebextensions deploy-dev/.ebextensions
          cp -r .platform deploy-dev/.platform
          cd deploy-dev && zip -r deploy-dev.zip .

      - name: Deploy to Elastic Beanstalk dev-server
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: daedong-breadmap
          environment_name: Daedongbreadmap-env
          version_label: Daedong Bread Map-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy-dev/deploy-dev.zip


